### ISSUE TITLE
Integration is choking after HA Core is updated to 2022.4.1

### ISSUE THREAD

**Issue by markaggar** [ardevd/ha-bobcatminer#6]
Logger: custom_components.bobcatminer
Source: custom_components/bobcatminer/__init__.py:36
Integration: Bobcat Miner
First occurred: 11:35:50 AM (109 occurrences)
Last logged: 1:56:40 PM

Unexpected error fetching bobcatminer data: invalid literal for int() with base 10: 'types.API\r'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/bobcatminer/__init__.py", line 36, in _update_method
    return await hass.async_add_executor_job(bobcat.status_summary)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/bobcatpy.py", line 56, in status_summary
    summary['miner_height'] = int(miner_status['miner_height'])
ValueError: invalid literal for int() with base 10: 'types.API\r'

**Comment by warmbadger** [comment]
I've updated and had no issues.  Could this just be related to the current API issues? [https://twitter.com/helium_status/status/1512492866383216640](url)

**Comment by ardevd** [comment]
Most likely related to the Helium API issues yesterday. Regardless, I need to implement some improved exception handling. Thanks for reporting the issue.

**Comment by ardevd** [comment]
Fixed with cd29ecd2739548e5f5ebea4ad35f6e695ccb5b24
